#this is the make file for project 0

CC = g++
CXXFLAGS = -Wall -std=c++11
TARGET = P0 
SRC = main.cpp tree.cpp
OBJ = main.o tree.o

$TARGET: $(OBJ)
	$(CC) $(CPPFLAGS) -o $(TARGET) $(OBJ)

%@    :  %@

clean :
	/bin/rm '-f' *.o $(TARGET)
